//! Used with zig compiler by zqjs CLI in runtime

const std = @import("std");

const constants = @import("constants.zig");

const OptLvl = enum {
    O0,
    O1,
    O2,
    O3,
    Os,
    Oz,
};

/// Bytecode generated by `qjsc` C identifier name
const BYTECODE_C_NAME = "b_c";

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const initFnName = b.option(
        []const u8,
        "init-fn-name",
        "Name of modules init function",
    );
    const zigRoot = b.option(
        []const u8,
        "zig-root",
        "Path to root zig file",
    );

    if (initFnName == null and zigRoot) {
        @panic("'-Dinit-fn-name' cannot be omitted when '-Dzig-root' is provided.");
    } else if (zigRoot == null and initFnName) {
        @panic("'-Dzig-root' cannot be omitted when '-Dinit-fn-name' is provided.");
    }

    const jsRoot = b.option(
        []const u8,
        "js-root",
        "Path to root js file",
    ) orelse {
        @panic("'-Djs-root' flag is required.");
    };
    const zqjsDir = b.option(
        []const u8,
        "zqjs-dir",
        "Path to the directory where 'zqjs' CLI, 'bld.zig' and quickjs soruce code files are located",
    ) orelse {
        @panic("'-Dzqjs-dir' flag is required");
    };

    const qjscOutputPath = std.mem.join(
        b.allocator,
        "/",
        &.{ b.tmpPath().src_path.sub_path, BYTECODE_C_NAME },
    );

    b.addSystemCommand(
        &.{std.mem.join(
            b.allocator,
            "/",

            &.{
                zqjsDir,
                constants.ExeDirPaths.qjscExe,
            },

            // Generate only bytecode
            "-c",

            // Strip debug bytecodes
            "-s",

            // Set the bytecode C identifier name
            "-N",
            BYTECODE_C_NAME,

            // Set the output file
            "-o",
            qjscOutputPath,

            // Input file
            jsRoot,
        )},
    );

    const zigRootLib = b.addLibrary(.{
        .name = "zig-root-lib",
        .root_module = b.createModule(.{
            .root_source_file = b.path(zigRoot),
            .target = target,
            .optimize = optimize,
        }),
        .linkage = .static,
    });

    const flto = b.option(
        bool,
        "flto",
        "Whether to enable '-flto' for quickjs C source files compilation",
    );

    const optLvl: []const u8 = switch (b.option(
        OptLvl,
        "opt-lvl",
        "Optimization level for quickjs C source files compilation",
    )) {
        .O0, null => "-O0",
        .O1 => "-O1",
        .O2 => "-O2",
        .O3 => "-O3",
        .Os => "-Os",
        .Oz => "-Oz",
    };

    zigRootLib.root_module.addCSourceFiles(.{
        .files = constants.QuickJsFileNames,
        .flags = &.{
            if (flto == true) "-flto" else "", optLvl,
        },
        .language = .c,
    });
}
