name: ci

on: '*'

jobs:
  ci:  
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
    
      - name: set up zig
        uses: mlugg/setup-zig@v2

      - name: build
        run: zig build
      
      - name: cache '.zig-cache'
        uses: actions/cache@v4
        with:
          path: ./.zig-cache

          key: zig-cache
