name: release draft

on: 
  push: 
    tags: 'v*'

permissions:
  contents: write

jobs: 
  release draft: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up zig
        uses: mlugg/setup-zig@v2

      - name: cache '.zig-cache'
        uses: actions/cache@v4
        with: 
          path: ./.zig-cache
          key: zig-cache

      
      - name: build
        run: | 
          VERSION=${{github.ref_name}}
          OPT="-Doptimize=ReleaseSmall -DoptimizeC"
          
          TARGET=x86_64-linux-gnu
          zig build $OPT -Dtarget=$TARGET -p $TARGET
          tar --zstd -cf zqjs-$VERSION-$TARGET.tar.zst -C $TARGET .

          TARGET=x86_64-linux-musl
          zig build $OPT -Dtarget=$TARGET -p $TARGET
          tar --zstd -cf zqjs-$VERSION-$TARGET.tar.zst -C $TARGET .

          TARGET=aarch64-linux-gnu
          zig build $OPT -Dtarget=$TARGET -p $TARGET
          tar --zstd -cf zqjs-$VERSION-$TARGET.tar.zst -C $TARGET .

          TARGET=aarch64-linux-musl
          zig build $OPT -Dtarget=$TARGET -p $TARGET
          tar --zstd -cf zqjs-$VERSION-$TARGET.tar.zst -C $TARGET .

          TARGET=x86_64-macos
          zig build $OPT -Dtarget=$TARGET -p $TARGET
          tar --zstd -cf zqjs-$VERSION-$TARGET.tar.zst -C $TARGET .

          TARGET=aarch64-macos
          zig build $OPT -Dtarget=$TARGET -p $TARGET
          tar --zstd -cf zqjs-$VERSION-$TARGET.tar.zst -C $TARGET .

          TARGET=x86_64-windows
          zig build $OPT -Dtarget=$TARGET-gnu -p $TARGET
          tar -caf zqjs-$VERSION-$TARGET.zip -C $TARGET .

          TARGET=aarch64-windows
          zig build $OPT -Dtarget=$TARGET-gnu -p $TARGET
          tar -caf zqjs-$VERSION-$TARGET.zip -C $TARGET .

      - name: create draft
        uses: softprops/action-gh-release@v2
        with:
          name: github.ref_name
          draft: true
          generate_release_notes: false
          files: | 
            zig-out/

      